# Generated by Django 3.0.8 on 2020-07-20 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_constructor', '0011_auto_20200719_1940'),
        ('testing', '0002_auto_20200720_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresult',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='test_code',
        ),
        migrations.AddField(
            model_name='optionresult',
            name='option',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_constructor.Option'),
        ),
        migrations.AddField(
            model_name='questionresult',
            name='question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_constructor.Question'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='amount_of_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_constructor.Test'),
        ),
    ]
