# Generated by Django 3.0.8 on 2020-07-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20200720_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresult',
            name='amount_of_points',
            field=models.IntegerField(default=0),
        ),
    ]
