# Generated by Django 3.0.8 on 2020-07-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_questionresult_amount_of_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresult',
            name='text_answer',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
