# Generated by Django 3.0.8 on 2020-07-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_auto_20200722_1649'),
        ('testing', '0005_auto_20200722_1103'),
    ]

    operations = [
    ]
