# Generated by Django 3.0.8 on 2020-07-10 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=100, verbose_name='название теста')),
                ('pub_date', models.DateTimeField(verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_options', models.BooleanField(verbose_name='тип вопроса')),
                ('text', models.TextField(verbose_name='текст вопроса')),
                ('image', models.ImageField(upload_to='', verbose_name='картинка')),
                ('options', models.TextField(verbose_name='варианты ответа')),
                ('correct_answers', models.TextField(verbose_name='правильные ответы')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_constructor.Test')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
