# Generated by Django 3.0.8 on 2020-07-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_constructor', '0006_auto_20200715_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='author',
        ),
    ]
