# Generated by Django 3.0.8 on 2020-07-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_constructor', '0009_auto_20200716_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options_count',
        ),
    ]
