# Generated by Django 3.0.8 on 2020-07-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_constructor', '0010_remove_question_options_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='test_title',
        ),
        migrations.AddField(
            model_name='question',
            name='amount_of_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='test_code',
            field=models.IntegerField(default=10000000),
        ),
        migrations.AddField(
            model_name='test',
            name='code',
            field=models.IntegerField(default=10000000),
        ),
    ]
